(load "match.scm")
(load "unittest.scm")

(test-equal (match "123456"                "123456")                        "")
(test-equal (match ""                      "")                              "")
(test-equal (match ""                      "123456")                        "")
(test-equal (match "123456"                "")                              "")
(test-equal (match "123456"                "654321")                        "")
(test-equal (match "(1234)"                "1234")                          "1234")
(test-equal (match "(1234)"                "4321")                          "")
(test-equal (match "(..)34"                "123456")                        "12")
(test-equal (match "12(..)56"              "123456")                        "34")
(test-equal (match "34(..)"                "123456")                        "56")
(test-equal (match "12(..)6"               "123456")                        "")
(test-equal (match "(..)45"                "123456")                        "23")
(test-equal (match "..(..)56"              "123456")                        "")
(test-equal (match "(A N)"                 "abc 123")                       "abc 123")
(test-equal (match "a(bc N)x"              "abc 123x")                      "bc 123")
(test-equal (match "a(bc N)4"              "abc 1234")                      "")
(test-equal (match "a(bc *)4"              "abc 1234")                      "bc 123")
(test-equal (match "a(bc A)z"              "abc xyz")                       "")
(test-equal (match "a(bc *)z"              "abc xyz")                       "bc xy")
(test-equal (match "4(N.N.)"               "aaa123456,78bbb")               "56,78b")
(test-equal (match "value: \"(N)\""        "This is the value: \"123\".")   "123")
(test-equal (match "text: (*)"             "text: abc 123.")                "abc 123.")
(test-equal (match "text: (*)."            "text: abc 123.")                "abc 123")
(test-equal (match "\"(A)\" is my name."   "Hello, \"Frank\" is my name.")  "Frank")
(test-equal (match "\"(A)\" is my name."   "Hello, \"Fra nk\" is my name.") "")
(test-equal (match "\"(A A)\" is my name." "Hello, \"Fra nk\" is my name.") "Fra nk")
(test-equal (match "start: (AN*)"          "start: ABC123xyz")              "ABC123xyz")
(test-equal (match "(A)123(A)"             "abc123def")                     "abcdef")

(test-equal (match? "(abc)"                "abc")                           #t)
(test-equal (match? "(abc)"                "cba")                           #f)
(test-equal (match? "a = (N)"              "a = 1")                         #t)
(test-equal (match? "a = (N)"              "a = b")                         #f)
